// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: speech.proto
#ifndef GRPC_speech_2eproto__INCLUDED
#define GRPC_speech_2eproto__INCLUDED

#include "speech.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace speech {

// ---------------grpc service---------------
class ASR GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Speech(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::speech::CLMOutput* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::speech::CLMOutput>> AsyncSpeech(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::speech::CLMOutput>>(AsyncSpeechRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::speech::CLMOutput>* AsyncSpeechRaw(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Speech(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::speech::CLMOutput* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::speech::CLMOutput>> AsyncSpeech(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::speech::CLMOutput>>(AsyncSpeechRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::speech::CLMOutput>* AsyncSpeechRaw(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_Speech_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Speech(::grpc::ServerContext* context, const ::speech::SpeechInput* request, ::speech::CLMOutput* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Speech : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Speech() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Speech() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Speech(::grpc::ServerContext* context, const ::speech::SpeechInput* request, ::speech::CLMOutput* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSpeech(::grpc::ServerContext* context, ::speech::SpeechInput* request, ::grpc::ServerAsyncResponseWriter< ::speech::CLMOutput>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Speech<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Speech : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Speech() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Speech() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Speech(::grpc::ServerContext* context, const ::speech::SpeechInput* request, ::speech::CLMOutput* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

class Speech GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SpeechRecognize(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::speech::SpeechOutput* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::speech::SpeechOutput>> AsyncSpeechRecognize(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::speech::SpeechOutput>>(AsyncSpeechRecognizeRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::speech::SpeechOutput>* AsyncSpeechRecognizeRaw(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SpeechRecognize(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::speech::SpeechOutput* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::speech::SpeechOutput>> AsyncSpeechRecognize(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::speech::SpeechOutput>>(AsyncSpeechRecognizeRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::speech::SpeechOutput>* AsyncSpeechRecognizeRaw(::grpc::ClientContext* context, const ::speech::SpeechInput& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_SpeechRecognize_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SpeechRecognize(::grpc::ServerContext* context, const ::speech::SpeechInput* request, ::speech::SpeechOutput* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SpeechRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SpeechRecognize() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SpeechRecognize() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpeechRecognize(::grpc::ServerContext* context, const ::speech::SpeechInput* request, ::speech::SpeechOutput* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSpeechRecognize(::grpc::ServerContext* context, ::speech::SpeechInput* request, ::grpc::ServerAsyncResponseWriter< ::speech::SpeechOutput>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SpeechRecognize<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_SpeechRecognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SpeechRecognize() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SpeechRecognize() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SpeechRecognize(::grpc::ServerContext* context, const ::speech::SpeechInput* request, ::speech::SpeechOutput* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

class CLM GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ContrainModel(::grpc::ClientContext* context, const ::speech::CLMInput& request, ::speech::CLMOutput* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::speech::CLMOutput>> AsyncContrainModel(::grpc::ClientContext* context, const ::speech::CLMInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::speech::CLMOutput>>(AsyncContrainModelRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::speech::CLMOutput>* AsyncContrainModelRaw(::grpc::ClientContext* context, const ::speech::CLMInput& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ContrainModel(::grpc::ClientContext* context, const ::speech::CLMInput& request, ::speech::CLMOutput* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::speech::CLMOutput>> AsyncContrainModel(::grpc::ClientContext* context, const ::speech::CLMInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::speech::CLMOutput>>(AsyncContrainModelRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::speech::CLMOutput>* AsyncContrainModelRaw(::grpc::ClientContext* context, const ::speech::CLMInput& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_ContrainModel_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ContrainModel(::grpc::ServerContext* context, const ::speech::CLMInput* request, ::speech::CLMOutput* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ContrainModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ContrainModel() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ContrainModel() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ContrainModel(::grpc::ServerContext* context, const ::speech::CLMInput* request, ::speech::CLMOutput* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestContrainModel(::grpc::ServerContext* context, ::speech::CLMInput* request, ::grpc::ServerAsyncResponseWriter< ::speech::CLMOutput>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ContrainModel<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_ContrainModel : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ContrainModel() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ContrainModel() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ContrainModel(::grpc::ServerContext* context, const ::speech::CLMInput* request, ::speech::CLMOutput* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace speech


#endif  // GRPC_speech_2eproto__INCLUDED
